export const themes = {
    light: 'light',
    dark: 'dark'
};

export const actionTypes = {
    SET_ACTIVE_COMMUNITY: 'SET_ACTIVE_COMMUNITY',
    SET_ACTIVE_ROOM: 'SET_ACTIVE_ROOM',
    SET_ACTIVE_MODAL: 'SET_ACTIVE_MODAL',
    SET_SEARCH_ACTIVE: 'SET_SEARCH_ACTIVE',
    TRIGGER_REFRESH: 'TRIGGER_REFRESH',
    TAG_SEARCH: 'TAG_SEARCH'
};

export const modalTypes = {
    COMMUNITY_SELECTOR: 'COMMUNITY_SELECTOR',
    COMMUNITY_DETAILS: 'COMMUNITY_DETAILS',
    ROOM_DETAILS: 'ROOM_DETAILS',
    NEW_POST: 'NEW_POST',
    POST_DETAILS: 'POST_DETAILS',
    CROSSPOST: 'CROSSPOST'
};

export const POSTS_PER_PAGE = 10;
