export const themes = {
    light: 'light',
    dark: 'dark'
};

export const actionTypes = {
    SET_ACTIVE_COMMUNITY: 'SET_ACTIVE_COMMUNITY',
    SET_ACTIVE_ROOM: 'SET_ACTIVE_ROOM',
    SET_ACTIVE_MODAL: 'SET_ACTIVE_MODAL',
    INCREMENT_PAGE: 'INCREMENT_PAGE',
    DECREMENT_PAGE: 'DECREMENT_PAGE'
};

export const modalTypes = {
    COMMUNITY_SELECTOR: 'COMMUNITY_SELECTOR',
    COMMUNITY_DETAILS: 'COMMUNITY_DETAILS',
    ROOM_DETAILS: 'ROOM_DETAILS',
    NEW_POST: 'NEW_POST',
    POST_DETAILS: 'POST_DETAILS'
};

export const POSTS_PER_PAGE = 5;
